// SPDX-License-Identifier: GPL-3.0-or-later
#include "card_formats.h"
#include <string.h>

#define FC8 {"Facility code", 0, 255, 0}
#define CN16 {"Card number", 0, 65535, 1}
#define FIELD(label, max, initial) {label, 0, max, initial}
const CardFormat card_formats[] = {
    {"HID H10301 (26-bit)",
     "H10301",
     "8-bit FC, 16-bit card. Parity is generated by firmware.",
     CardHid26,
     3,
     2,
     {FC8, CN16}},
    {"EM4100 (RF/64)",
     "EM4100",
     "EM IDs have a 16-bit prefix. This uses Flipper's FC/card display convention.",
     CardEm,
     5,
     3,
     {FC8, CN16, FIELD("ID prefix", 65535, 0)}},
    {"EM4100 (RF/32)",
     "EM4100/32",
     "EM IDs have a 16-bit prefix. This uses Flipper's FC/card display convention.",
     CardEm,
     5,
     3,
     {FC8, CN16, FIELD("ID prefix", 65535, 0)}},
    {"EM4100 (RF/16)",
     "EM4100/16",
     "EM IDs have a 16-bit prefix. This uses Flipper's FC/card display convention.",
     CardEm,
     5,
     3,
     {FC8, CN16, FIELD("ID prefix", 65535, 0)}},
    {"Indala (26-bit)",
     "Indala26",
     "Includes Wiegand parity and Indala checksum.",
     CardIndala,
     4,
     2,
     {FC8, CN16}},
    {"IO Prox XSF",
     "IOProxXSF",
     "Version is part of the credential. Match the original card.",
     CardIo,
     4,
     3,
     {FC8, CN16, FIELD("Version", 255, 0)}},
    {"AWID (26-bit)",
     "AWID",
     "26-bit Wiegand payload with even/odd parity.",
     CardAwid,
     9,
     2,
     {FC8, CN16}},
    {"Pyramid (26-bit)",
     "Pyramid",
     "26-bit layout. Firmware generates parity and checksum.",
     CardPyramid,
     4,
     2,
     {FC8, CN16}},
    {"Gallagher",
     "Gallagher",
     "Region and issue level are part of the credential. FC is 16 bits; card is 24 bits on air.",
     CardGallagher,
     8,
     4,
     {FIELD("Facility code", 65535, 0), FIELD("Card number", 16777215, 1), FIELD("Region", 15, 0),
      FIELD("Issue level", 15, 0)}},
    {"Keri",
     "Keri",
     "5-bit facility code and 22-bit card number.",
     CardKeri,
     4,
     2,
     {FIELD("Facility code", 31, 0), FIELD("Card number", 4194303, 1)}},
    {"Securakey (26-bit)",
     "Securakey",
     "FC 0 selects a different format. Check bytes must match the card; their algorithm is "
     "undocumented in the SDK.",
     CardSecurakey,
     6,
     4,
     {{"Facility code", 1, 255, 1},
      CN16,
      FIELD("Check byte 1", 255, 0),
      FIELD("Check byte 2", 255, 0)}},
    {"Viking",
     "Viking",
     "This protocol uses an ID; it has no facility-code field.",
     CardId,
     4,
     1,
     {FIELD("Card ID", UINT32_MAX, 1)}},
    {"PAC/Stanley",
     "PAC/Stanley",
     "This protocol uses an ID; it has no facility-code field.",
     CardId,
     4,
     1,
     {FIELD("Card ID", UINT32_MAX, 1)}},
    {"Jablotron",
     "Jablotron",
     "40-bit card data entered as a decimal integer. No facility code.",
     CardId,
     5,
     1,
     {FIELD("Card data", 1099511627775ULL, 1)}},
    {"IDTECK",
     "Idteck",
     "Factory word defaults to the IDTK preamble. It is not a site facility code.",
     CardIdteck,
     8,
     2,
     {FIELD("Card ID", UINT32_MAX, 1), {"Factory word", 1229214795, 1229214795, 1229214795}}},
    {"Paradox",
     "Paradox",
     "8-bit FC, 16-bit card. Includes the Paradox CRC.",
     CardParadox,
     6,
     2,
     {FC8, CN16}},
    {"GProx II (26-bit)",
     "GProxII",
     "Profile is part of the credential. Uses the 26-bit layout.",
     CardGprox,
     12,
     3,
     {FC8, CN16, FIELD("Profile", 65535, 256)}},
    {"HID H10306 (34-bit)",
     "HIDProx",
     "H10306 layout: 16-bit facility code and 16-bit card number.",
     CardHid34,
     6,
     2,
     {FIELD("Facility code", 65535, 0), CN16}},
};
const size_t card_format_count = sizeof(card_formats) / sizeof(card_formats[0]);

static uint64_t get(const uint8_t *data, unsigned start, unsigned width) {
    uint64_t value = 0;
    for(unsigned i = 0; i < width; ++i) {
        unsigned pos = start + i;
        value = (value << 1) | ((data[pos / 8] >> (7 - pos % 8)) & 1);
    }
    return value;
}

bool card_parse_decimal(const char *text, uint64_t min, uint64_t max, uint64_t *value) {
    if(!text || !*text || min > max)
        return false;
    uint64_t n = 0;
    for(; *text; ++text) {
        if(*text < '0' || *text > '9')
            return false;
        unsigned digit = (unsigned)(*text - '0');
        if(digit > max || n > (max - digit) / 10)
            return false;
        n = n * 10 + digit;
    }
    if(n < min)
        return false;
    *value = n;
    return true;
}

static void put(uint8_t *data, unsigned start, unsigned width, uint64_t value) {
    for(unsigned i = 0; i < width; ++i) {
        unsigned pos = start + i;
        uint8_t mask = 1U << (7 - pos % 8);
        if((value >> (width - 1 - i)) & 1)
            data[pos / 8] |= mask;
        else
            data[pos / 8] &= (uint8_t)~mask;
    }
}
static unsigned parity(uint64_t value) {
    unsigned result = 0;
    while(value) {
        result ^= value & 1;
        value >>= 1;
    }
    return result;
}
static uint8_t reverse(uint8_t value) {
    uint8_t result = 0;
    for(unsigned i = 0; i < 8; ++i) {
        result = (result << 1) | (value & 1);
        value >>= 1;
    }
    return result;
}
static uint64_t wiegand26(uint64_t fc, uint64_t cn) {
    uint64_t value = (fc << 16) | cn;
    return ((uint64_t)parity(value >> 12) << 25) | (value << 1) | (parity(value & 4095) ^ 1);
}
size_t card_proxmark_raw(const CardFormat *f, const uint8_t *d, size_t size, uint8_t *raw,
                         size_t capacity) {
    if(!f || !d || !raw || size != f->size)
        return 0;
    size_t length;
    switch(f->encoding) {
    case CardHid26:
    case CardHid34:
    case CardEm:
        length = 5;
        break;
    case CardIndala:
        length = 8;
        break;
    case CardAwid:
        length = 12;
        break;
    default:
        return 0;
    }
    if(capacity < length)
        return 0;
    memset(raw, 0, length);
    switch(f->encoding) {
    case CardHid26:
        // Proxmark HID transport: standard header, length sentinel, Wiegand parity.
        put(raw, 0, 40, (UINT64_C(1) << 37) | (UINT64_C(1) << 26) | wiegand26(d[0], get(d, 8, 16)));
        break;
    case CardHid34:
        put(raw, 0, 40, get(d, 0, 44));
        break;
    case CardEm:
        // EM410x commands take the complete 40-bit ID, without RF parity/framing.
        memcpy(raw, d, 5);
        break;
    case CardIndala:
        raw[0] = 0xA0;
        put(raw, 32, 1, 1);
        put(raw, 33, 27, get(d, 0, 27));
        put(raw, 62, 2, get(d, 27, 2));
        break;
    case CardAwid:
        raw[0] = 1;
        for(unsigned i = 0; i < 22; ++i) {
            uint64_t group = get(d, i * 3, 3);
            put(raw, 8 + i * 4, 4, (group << 1) | (parity(group) ^ 1));
        }
        break;
    default:
        return 0;
    }
    return length;
}
static uint8_t paradox_crc(uint64_t fc, uint64_t cn) {
    uint64_t payload = (fc << 16) | cn;
    uint8_t manchester[9] = {0};
    // Four leading zero bits, then Manchester coding of ten zero bits + FC + CN.
    for(unsigned i = 0; i < 34; ++i) {
        unsigned bit = (payload >> (33 - i)) & 1;
        put(manchester, 4 + i * 2, 2, bit ? 2 : 1);
    }
    uint8_t crc = 0;
    for(unsigned i = 0; i < 9; ++i) {
        crc ^= reverse(manchester[i]);
        for(unsigned j = 0; j < 8; ++j)
            crc = (crc << 1) ^ ((crc & 128) ? 0x31 : 0);
    }
    return reverse(crc) ^ 6;
}

bool card_encode(const CardFormat *f, const uint64_t *v, uint8_t *d, size_t size) {
    if(!f || !v || !d || size != f->size)
        return false;
    for(size_t i = 0; i < f->count; ++i)
        if(v[i] < f->fields[i].min || v[i] > f->fields[i].max)
            return false;
    memset(d, 0, size);
    switch(f->encoding) {
    case CardHid26:
        put(d, 0, 8, v[0]);
        put(d, 8, 16, v[1]);
        break;
    case CardEm:
        put(d, 0, 16, v[2]);
        put(d, 16, 8, v[0]);
        put(d, 24, 16, v[1]);
        break;
    case CardIo:
        put(d, 0, 8, v[0]);
        put(d, 8, 8, v[2]);
        put(d, 16, 16, v[1]);
        break;
    case CardAwid:
        put(d, 0, 8, 26);
        put(d, 8, 26, wiegand26(v[0], v[1]));
        break;
    case CardPyramid:
        put(d, 0, 8, 26);
        put(d, 8, 8, v[0]);
        put(d, 16, 16, v[1]);
        break;
    case CardGallagher:
        put(d, 0, 4, v[2]);
        put(d, 4, 4, v[3]);
        put(d, 8, 24, v[0]);
        put(d, 32, 32, v[1]);
        break;
    case CardSecurakey:
        put(d, 0, 16, v[0]);
        put(d, 16, 16, v[1]);
        put(d, 32, 8, v[2]);
        put(d, 40, 8, v[3]);
        break;
    case CardId:
        put(d, 0, size * 8, v[0]);
        break;
    case CardIdteck:
        put(d, 0, 32, v[1]);
        put(d, 32, 32, v[0]);
        break;
    case CardParadox:
        put(d, 10, 8, v[0]);
        put(d, 18, 16, v[1]);
        put(d, 34, 8, paradox_crc(v[0], v[1]));
        break;
    case CardIndala: {
        const unsigned fc_bits[] = {24, 16, 11, 14, 15, 20, 6, 25};
        const unsigned cn_bits[] = {9, 12, 10, 7, 19, 3, 2, 18, 13, 0, 4, 21, 23, 26, 17, 8};
        for(unsigned i = 0; i < 8; ++i)
            put(d, fc_bits[i], 1, (v[0] >> (7 - i)) & 1);
        for(unsigned i = 0; i < 16; ++i)
            put(d, cn_bits[i], 1, (v[1] >> (15 - i)) & 1);
        uint64_t value = (v[0] << 16) | v[1];
        put(d, 1, 1, parity(value >> 12));
        put(d, 5, 1, parity(value & 4095) ^ 1);
        const unsigned checks[] = {14, 12, 9, 8, 6, 5, 2, 0};
        unsigned check = 0;
        for(unsigned i = 0; i < 8; ++i)
            check ^= (value >> checks[i]) & 1;
        put(d, 27, 2, check ? 1 : 2);
        break;
    }
    case CardKeri: {
        const int cn_map[] = {-1, -1, -1, -1, 13, 12, 20, 5,  16, 6,  21, 17, 8, -1, 0,  7,
                              10, 15, -1, 11, 4,  1,  -1, 18, -1, 19, 2,  14, 3, 9,  -1, -1};
        const int fc_map[] = {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0,  -1, -1,
                              -1, -1, 2,  -1, -1, -1, 3,  -1, 4,  -1, -1, -1, -1, -1, 1,  -1};
        uint32_t id = 0x80000000;
        for(unsigned i = 0; i < 32; ++i) {
            if(cn_map[i] >= 0)
                id |= ((v[1] >> cn_map[i]) & 1) << i;
            if(fc_map[i] >= 0)
                id |= ((v[0] >> fc_map[i]) & 1) << i;
        }
        put(d, 0, 32, id);
        break;
    }
    case CardGprox: {
        uint8_t plain[9] = {0};
        put(plain, 0, 8, 0x90);
        put(plain, 8, 6, 26);
        put(plain, 14, 2, 3);
        put(plain, 16, 16, v[2]);
        put(plain, 32, 26, wiegand26(v[0], v[1]));
        for(unsigned i = 1; i < 9; ++i)
            plain[i] ^= plain[0];
        put(d, 0, 6, 62);
        for(unsigned i = 0; i < 9; ++i) {
            uint8_t b = reverse(plain[i]);
            put(d, 6 + i * 10, 4, b >> 4);
            put(d, 11 + i * 10, 4, b & 15);
        }
        break;
    }
    case CardHid34: {
        uint64_t value = (v[0] << 16) | v[1];
        put(d, 6, 1, 1);
        put(d, 9, 1, 1); // HID 44-bit size header for 34-bit data
        put(d, 10, 1, parity(value >> 16));
        put(d, 11, 32, value);
        put(d, 43, 1, parity(value & 65535) ^ 1);
        break;
    }
    default:
        return false;
    }
    return true;
}

bool card_decode(const CardFormat *f, const uint8_t *d, size_t size, uint64_t *values) {
    uint8_t canonical[12];
    uint64_t v[CARD_MAX_FIELDS] = {0};
    if(!f || !d || !values || size != f->size || size > sizeof(canonical))
        return false;
    switch(f->encoding) {
    case CardHid26:
        v[0] = get(d, 0, 8);
        v[1] = get(d, 8, 16);
        break;
    case CardEm:
        v[0] = get(d, 16, 8);
        v[1] = get(d, 24, 16);
        v[2] = get(d, 0, 16);
        break;
    case CardIo:
        v[0] = get(d, 0, 8);
        v[1] = get(d, 16, 16);
        v[2] = get(d, 8, 8);
        break;
    case CardAwid:
        if(d[0] != 26)
            return false;
        v[0] = get(d, 9, 8);
        v[1] = get(d, 17, 16);
        break;
    case CardPyramid:
        if(d[0] != 26)
            return false;
        v[0] = get(d, 8, 8);
        v[1] = get(d, 16, 16);
        break;
    case CardGallagher:
        v[0] = get(d, 8, 24);
        v[1] = get(d, 32, 32);
        v[2] = get(d, 0, 4);
        v[3] = get(d, 4, 4);
        break;
    case CardSecurakey:
        v[0] = get(d, 0, 16);
        v[1] = get(d, 16, 16);
        v[2] = d[4];
        v[3] = d[5];
        break;
    case CardId:
        v[0] = get(d, 0, size * 8);
        break;
    case CardIdteck:
        v[0] = get(d, 32, 32);
        v[1] = get(d, 0, 32);
        break;
    case CardParadox:
        v[0] = get(d, 10, 8);
        v[1] = get(d, 18, 16);
        break;
    case CardIndala: {
        const unsigned fc_bits[] = {24, 16, 11, 14, 15, 20, 6, 25};
        const unsigned cn_bits[] = {9, 12, 10, 7, 19, 3, 2, 18, 13, 0, 4, 21, 23, 26, 17, 8};
        for(unsigned i = 0; i < 8; ++i)
            v[0] = (v[0] << 1) | get(d, fc_bits[i], 1);
        for(unsigned i = 0; i < 16; ++i)
            v[1] = (v[1] << 1) | get(d, cn_bits[i], 1);
        break;
    }
    case CardKeri: {
        const unsigned fc_pos[] = {13, 30, 18, 22, 24};
        const unsigned cn_pos[] = {14, 21, 26, 28, 20, 7, 9,  15, 12, 29, 16,
                                   19, 5,  4,  27, 17, 8, 11, 23, 25, 6,  10};
        uint64_t id = get(d, 0, 32);
        for(unsigned i = 0; i < 5; ++i)
            v[0] |= ((id >> fc_pos[i]) & 1) << i;
        for(unsigned i = 0; i < 22; ++i)
            v[1] |= ((id >> cn_pos[i]) & 1) << i;
        break;
    }
    case CardGprox: {
        uint8_t plain[9];
        for(unsigned i = 0; i < 9; ++i) {
            uint8_t b = (get(d, 6 + i * 10, 4) << 4) | get(d, 11 + i * 10, 4);
            plain[i] = reverse(b);
            if(i)
                plain[i] ^= plain[0];
        }
        if(get(plain, 8, 6) != 26)
            return false;
        v[0] = get(plain, 33, 8);
        v[1] = get(plain, 41, 16);
        v[2] = get(plain, 16, 16);
        break;
    }
    case CardHid34:
        v[0] = get(d, 11, 16);
        v[1] = get(d, 27, 16);
        break;
    default:
        return false;
    }
    // An unknown layout, check bit, or extra payload stays in the raw editor.
    // Never discard information merely to make a file fit a decimal preset.
    if(!card_encode(f, v, canonical, size) || memcmp(canonical, d, size) != 0)
        return false;
    memcpy(values, v, f->count * sizeof(*v));
    return true;
}
